# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción

In [1]:
# cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Cargamos el modelo
import pickle
filename = 'modelo-reg (1).pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))

In [3]:
#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

         videojuego  Edad    Sexo      Plataforma  Consumidor_habitual
0     'Mass Effect'    33  Hombre           Otros                False
1  'KOA: Reckoning'    30   Mujer              PC                 True
2      'Dead Space'    22  Hombre          'Xbox'                False
3          'Crysis'    17  Hombre  'Play Station'                False
4        'Sim City'    27   Mujer           Otros                 True

In [ ]:
# Aquí va la interfaz gráfica
#Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos



import streamlit as st



st.title('Predicción de inversión en una tienda de videojuegos')



Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)

videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])

Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])

Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])

Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])





#Dataframe

datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]

data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

In [4]:
#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

,Edad,videojuego_'Crysis',videojuego_'Dead Space',videojuego_'KOA: Reckoning',videojuego_'Mass Effect',videojuego_'Sim City',Plataforma_'Play Station',Plataforma_'Xbox',Plataforma_Otros,Plataforma_PC,Sexo_Hombre,Sexo_Mujer,Consumidor_habitual_False,Consumidor_habitual_True
0,33,0,0,0,1,0,0,0,1,0,1,0,1,0
1,30,0,0,1,0,0,0,0,0,1,0,1,0,1
2,22,0,1,0,0,0,0,1,0,0,1,0,1,0
3,17,1,0,0,0,0,1,0,0,0,1,0,1,0
4,27,0,0,0,0,1,0,0,1,0,0,1,0,1

In [6]:
#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

,Edad,videojuego_'Battlefield',videojuego_'Crysis',videojuego_'Dead Space',videojuego_'F1',videojuego_'Fifa',videojuego_'KOA: Reckoning',videojuego_'Mass Effect',videojuego_'Sim City',Plataforma_'Play Station',Plataforma_'Xbox',Plataforma_Otros,Plataforma_PC,Sexo_Mujer,Consumidor_habitual_True
0,33,0,0,0,0,0,0,1,0,0,0,1,0,0,0
1,30,0,0,0,0,0,1,0,0,0,0,0,1,1,1
2,22,0,0,1,0,0,0,0,0,0,1,0,0,0,0
3,17,0,1,0,0,0,0,0,0,1,0,0,0,0,0
4,27,0,0,0,0,0,0,0,1,0,0,1,0,1,1

In [ ]:
#Se normaliza la edad para predecir con Knn, Red, SVM
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

# **Predicciones**

In [7]:
#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

[33879.46277828 30317.49826779 20907.385074   16803.60702482
 26848.12036619]

In [8]:
data['Prediccion']=Y_pred
data.head()

,videojuego,Edad,Sexo,Plataforma,Consumidor_habitual,Prediccion
0,'Mass Effect',33,Hombre,Otros,False,33879.462778
1,'KOA: Reckoning',30,Mujer,PC,True,30317.498268
2,'Dead Space',22,Hombre,'Xbox',False,20907.385074
3,'Crysis',17,Hombre,'Play Station',False,16803.607025
4,'Sim City',27,Mujer,Otros,True,26848.120366

In [9]:
#predicciones finales
data

,videojuego,Edad,Sexo,Plataforma,Consumidor_habitual,Prediccion
0,'Mass Effect',33,Hombre,Otros,False,33879.462778
1,'KOA: Reckoning',30,Mujer,PC,True,30317.498268
2,'Dead Space',22,Hombre,'Xbox',False,20907.385074
3,'Crysis',17,Hombre,'Play Station',False,16803.607025
4,'Sim City',27,Mujer,Otros,True,26848.120366

In [ ]:
# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 6.55%")